networks:
  cssninja-services:
    external: true

services:
  hr-demo:
    image: digisquad/cssninja.hr-demo:latest
    networks:
      - cssninja-services
    restart: 'unless-stopped'
    labels:
      traefik.enable: true
      traefik.docker.network: 'cssninja-services'
      traefik.http.routers.hr-demo.entrypoints: 'http'
      traefik.http.routers.hr-demo.rule: 'Host(`hr.${HOST:-127.0.0.1.nip.io}`)'
      traefik.http.routers.hr-demo.middlewares: 'https-redirect@docker'
      traefik.http.routers.hr-demo.service: 'hr-demo-https'
      traefik.http.services.hr-demo-https.loadbalancer.server.port: 8080
      traefik.http.routers.hr-demo-https.rule: 'Host(`hr.${HOST:-127.0.0.1.nip.io}`)'
      traefik.http.routers.hr-demo-https.tls: true
      traefik.http.routers.hr-demo-https.entrypoints: 'https'
      traefik.http.routers.hr-demo-https.tls.certresolver: 'http'
      traefik.http.routers.hr-demo-https.service: 'hr-demo-https'

  hr-api:
    image: digisquad/cssninja.hr-api:latest
    networks:
      - cssninja-services
    restart: 'unless-stopped'
    labels:
      traefik.enable: true
      traefik.docker.network: 'cssninja-services'
      traefik.http.routers.hr-api.entrypoints: 'http'
      traefik.http.routers.hr-api.rule: 'Host(`api-hr.${HOST:-127.0.0.1.nip.io}`)'
      traefik.http.routers.hr-api.middlewares: 'https-redirect@docker'
      traefik.http.routers.hr-api.service: 'hr-api-https'
      traefik.http.services.hr-api-https.loadbalancer.server.port: 8090
      traefik.http.routers.hr-api-https.rule: 'Host(`api-hr.${HOST:-127.0.0.1.nip.io}`)'
      traefik.http.routers.hr-api-https.tls: true
      traefik.http.routers.hr-api-https.entrypoints: 'https'
      traefik.http.routers.hr-api-https.tls.certresolver: 'http'
      traefik.http.routers.hr-api-https.service: 'hr-api-https'

