name: 'build template'
description: 'build template archive'
# We declare that the action takes two arguments in input
inputs:
  project:
    description: 'Project'
    required: true
  tag:
    description: 'Tag'
    required: true
# And ouput one variable that will be available by the workflow
outputs:
  filepath:
    description: "template archive path"
    value: ${{ steps.build.outputs.filepath }}
runs:
  using: "composite"
  steps:
    # Ensure that zip is installed
    - run: sudo apt-get install zip
      shell: bash
    # Here we pass our inputs to the script.sh
    - id: build
      run: ${{ github.action_path }}/script.sh ${{inputs.project}} ${{inputs.tag}}
      shell: bash